/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package digitalsound;

//import clases.Conexion;
import clases.DataSourceManager;
import clases.Empleados;
import clases.ProductoApartado;
import clases.Ticket;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author parti
 */
public class listapartados extends javax.swing.JFrame {
    Empleados mEmpleados = new Empleados();
    DataSourceManager dsm = new DataSourceManager();
    //Conexion mConexion;
    ProductoApartado mProductoApartado;
    ArrayList mListaApartados;
    ArrayList mListaProductos;
    int id;
    //private static Connection Conection;
    //private static Statement Sentencia;
    //private static ResultSet Resultado;
    /**
     * Creates new form listapartados
     */
    public listapartados(Empleados empleados) {
        initComponents();
        //mConexion = new Conexion("sistemaapartado","root","");
        mEmpleados = empleados;
        Usuarios();
        llenarLApartados();
        configurarVentana();
    }
    private void configurarVentana(){
        this.setLocationRelativeTo(null);
        this.setResizable(false);
        this.setTitle("Digital Sound - Lista de apartados");
    }
    private void Usuarios(){
        lbl_usuario.setText(mEmpleados.getNombre().trim());
        lbl_tipo.setText(mEmpleados.getTipo().trim());        
        dsm.setTipo(mEmpleados.getTipo());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        lbl_id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_productos = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_apartados = new javax.swing.JTable();
        btnagregar = new javax.swing.JButton();
        btnsalir = new javax.swing.JButton();
        btn_abonar = new javax.swing.JButton();
        btn_menu = new javax.swing.JButton();
        btn_abonar1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        lbl_tipo = new javax.swing.JLabel();
        lbl_usuario = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_cerrar_sesion = new javax.swing.JButton();

        jScrollPane1.setViewportView(jEditorPane1);

        lbl_id.setText("jLabel2");

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(208, 31, 36));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tb_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tb_productos.setFocusable(false);
        tb_productos.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(tb_productos);

        tb_apartados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "CLIENTE", "FECHA", "DESCRIPCION"
            }
        ));
        tb_apartados.setCellSelectionEnabled(true);
        tb_apartados.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tb_apartadosMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tb_apartados);

        btnagregar.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        btnagregar.setForeground(new java.awt.Color(0, 153, 0));
        btnagregar.setText("AGREGAR");
        btnagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnagregarActionPerformed(evt);
            }
        });

        btnsalir.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        btnsalir.setForeground(new java.awt.Color(208, 31, 36));
        btnsalir.setText("SALIR");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        btn_abonar.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        btn_abonar.setForeground(new java.awt.Color(51, 51, 51));
        btn_abonar.setText("ABONAR");
        btn_abonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abonarActionPerformed(evt);
            }
        });

        btn_menu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btn_menu.setText("MENU");
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_abonar1.setFont(new java.awt.Font("Source Sans Pro Black", 1, 12)); // NOI18N
        btn_abonar1.setForeground(new java.awt.Color(51, 51, 51));
        btn_abonar1.setText("HISTORIAL ABONOS");
        btn_abonar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_abonar1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_menu)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(btnsalir)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btn_abonar1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btn_abonar)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnagregar))
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 524, Short.MAX_VALUE)
                        .addComponent(jScrollPane2)))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btn_menu)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnsalir)
                    .addComponent(btn_abonar, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_abonar1, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(208, 31, 36));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/recursos/soundchico.png"))); // NOI18N

        jLabel7.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Puesto:");

        lbl_tipo.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_tipo.setForeground(new java.awt.Color(255, 255, 255));

        lbl_usuario.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        lbl_usuario.setForeground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Usuario:");

        btn_cerrar_sesion.setFont(new java.awt.Font("Roboto", 1, 18)); // NOI18N
        btn_cerrar_sesion.setText("Cerrar Sesion");
        btn_cerrar_sesion.setFocusable(false);
        btn_cerrar_sesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cerrar_sesionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(btn_cerrar_sesion)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lbl_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(lbl_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cerrar_sesion)
                .addGap(94, 94, 94)
                .addComponent(jLabel1)
                .addContainerGap(118, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        MenuInicio menu = new MenuInicio(mEmpleados);
        menu.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_abonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abonarActionPerformed
        try{
            int id = (int) tb_apartados.getValueAt(tb_apartados.getSelectedRow(), 0); //obtener id del apartado
            Abono abono = new Abono(id, this, mEmpleados); //crear la ventana de los abonos con la id seleccionada
            abono.setVisible(true); //hacerla visible
        }catch(ArrayIndexOutOfBoundsException e){ //manejo de excepción si no se selecciona ninguna fila
            JOptionPane.showMessageDialog(null, "Necesita seleccionar un apartado para abonar");
            e.printStackTrace();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_btn_abonarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        System.exit(0);

    }//GEN-LAST:event_btnsalirActionPerformed

    private void btnagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnagregarActionPerformed
        SeleccionNuevo seleccion = new SeleccionNuevo(mEmpleados);
        seleccion.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnagregarActionPerformed

    private void tb_apartadosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tb_apartadosMouseClicked
        llenarLProductos(1);
        id = (int) tb_apartados.getValueAt(tb_apartados.getSelectedRow(), 0);
    }//GEN-LAST:event_tb_apartadosMouseClicked

    private void btn_cerrar_sesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cerrar_sesionActionPerformed
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_cerrar_sesionActionPerformed

    private void btn_abonar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_abonar1ActionPerformed
        int id = (Integer) tb_apartados.getValueAt(tb_apartados.getSelectedRow(), 0);
        ConsultaAbonos consulta = new ConsultaAbonos(id, mEmpleados, this, mProductoApartado);
        consulta.setVisible(true);
    }//GEN-LAST:event_btn_abonar1ActionPerformed

    //METODO PARA LLENAR LA TABLA tb_apartados
    public void llenarLApartados() {
            // Crea un DefaultTableModel con los nombres de las columnas
           DefaultTableModel tableModel = new DefaultTableModel(new String[]{"ID","CLIENTE", "FECHA", "TOTAL", "SALDO"}, 0) {
        @Override
        // Bloquea todas las celdas para que no sean editables
        public boolean isCellEditable(int row, int column) {
            return false; 
        }
        };
           try{
               mListaApartados = getListaApartados();
           }catch(SQLException e){
               e.printStackTrace();
           }
            Iterator<Ticket> iterador = mListaApartados.iterator();
            while (iterador.hasNext()) {
                Ticket mTicket = iterador.next();
                System.out.println("Agregando Ticket: " + mTicket);
                tableModel.addRow(new Object[]{mTicket.getIdTicket(), mTicket.getCliente(), mTicket.getFecha(), mTicket.getTotal(), mTicket.getSaldo()});
            }
            tb_apartados.setModel(tableModel);
        }
        public ArrayList getListaApartados() throws SQLException{
        ArrayList mListaApartados = new ArrayList();
        Ticket mTicket = null;
        Connection con = null;
        PreparedStatement pst = null;
        ResultSet rs = null;
        try{
            
            con = dsm.getDataSource().getConnection();
            pst = con.prepareStatement("CALL consulta_apartados();");
            rs = pst.executeQuery();
            
            while(rs.next()){
                System.out.println("Procesando fila...");
                mTicket = new Ticket();
                mTicket.setIdTicket(rs.getInt("ID"));
                mTicket.setCliente(rs.getString("CLIENTE"));
                mTicket.setFecha(rs.getString("FECHA"));
                mTicket.setTotal(rs.getString("TOTAL"));
                mTicket.setSaldo(rs.getString("SALDO"));
                mListaApartados.add(mTicket);                
            }
            System.out.println("Se ha procesado todo el ResultSet");
        }catch(SQLException e){
            e.printStackTrace();
        }
        finally{
            if(rs != null){
                rs.close();
            }
            if(pst != null){
                pst.close();
            }
            if(con != null){
                con.close();
            }
        }
        return mListaApartados;
    }
    
        //METODO PARA LLENAR LA TABLA tb_productos
        public void llenarLProductos(int id) {
            // Crea un DefaultTableModel con los nombres de las columnas
           DefaultTableModel tableModel = new DefaultTableModel(new String[]{"PRODUCTO", "PRECIO UNITARIO", "CANTIDAD", "TOTAL", "SALDO"}, 0) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // Bloquea todas las celdas para que no sean editables
        }
        };
            // Obtiene la lista de equipos de la base de datos
            try{
                mListaProductos = getListaProductos(id);
            }catch(SQLException e){
                e.printStackTrace();
            }
            // Itera sobre la lista de equipos y añade cada uno al tableModel
            Iterator<ProductoApartado> iterador = mListaProductos.iterator();
            while (iterador.hasNext()) {
                mProductoApartado = iterador.next();
                System.out.println("Agregando Ticket: " + mProductoApartado);

                // Añade una fila con los datos de cada objeto Equipos
                tableModel.addRow(new Object[]{mProductoApartado.getNombre(), mProductoApartado.getPrecio(), mProductoApartado.getCantidad(), mProductoApartado.getTotal(), mProductoApartado.getSaldo()});
            }

            // Asigna el DefaultTableModel a la JTable
            tb_productos.setModel(tableModel);
        }
        public ArrayList getListaProductos(int estado) throws SQLException{
            ArrayList mListaProductos = new ArrayList();
            ProductoApartado mProductoApartado = null;
            Connection con = null;
            PreparedStatement pst = null;
            ResultSet rs = null;
            try{
                con = dsm.getDataSource().getConnection();
                pst = con.prepareStatement("CALL buscar_producto_apartado(?);");
                pst.setInt(1, id); //Obtiene el nombre para añadirlo a la consulta
                lbl_id.setText(""+id);
                rs = pst.executeQuery();
                while(rs.next()){
                    System.out.println("Procesando fila...");
                    mProductoApartado = new ProductoApartado();
                    mProductoApartado.setIdReserva(id);
                    mProductoApartado.setIdProdApartado(rs.getInt("idProdApartado"));
                    mProductoApartado.setNombre(rs.getString("p.NombreProducto"));
                    mProductoApartado.setId(rs.getString("p.idProducto"));
                    mProductoApartado.setPrecio(rs.getDouble("p.precio"));
                    mProductoApartado.setCantidad(rs.getInt("pa.cantidad"));
                    mProductoApartado.setTotal(rs.getDouble("total"));
                    mProductoApartado.setSaldo(rs.getDouble("SALDO"));
                    mListaProductos.add(mProductoApartado);                
                } 
            }catch(SQLException e){
                e.printStackTrace();
            }finally{
                if(rs != null){
                    rs.close();
                }
                if(pst != null){
                    pst.close();
                }
                if(con != null){
                    con.close();
                }
            }
            return mListaProductos;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(listapartados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(listapartados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(listapartados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(listapartados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Empleados mEmpleados = new Empleados();
                new listapartados(mEmpleados).setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_abonar;
    private javax.swing.JButton btn_abonar1;
    private javax.swing.JButton btn_cerrar_sesion;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btnagregar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lbl_id;
    private javax.swing.JLabel lbl_tipo;
    private javax.swing.JLabel lbl_usuario;
    private javax.swing.JTable tb_apartados;
    private javax.swing.JTable tb_productos;
    // End of variables declaration//GEN-END:variables
}
